description: Settings for the photochemical model.

atmosphere-grid:
  bottom: 0.0 # cm
  top: 1.0e7 # cm
  number-of-layers: 200

photolysis-grid:
  regular-grid: true
  lower-wavelength: 92.5 # nm
  upper-wavelength: 855.0 # nm
  number-of-bins: 200

planet:
  use-background-gas: true
  background-gas: H2
  surface-pressure: 1.013
  planet-mass: 5.972e27 
  planet-radius: 6.371e8
  surface-albedo: 0.25
  diurnal-averaging-factor: 0.5
  solar-zenith-angle: 50.0
  diff-lim-hydrogen-escape: true
  water:
    fix-water-in-troposphere: false
    water-condensation: true
    gas-rainout: true
    rainfall-rate: 1
    rainout-species: [H2SO4aer, S8aer, HCaer1, HCaer2, HCaer3,
                      OH, H2S, SO2, CS2, OCS, CN, HCN, NH3, C2H4,
                      "NO", HO2, N2O, H2O2, O3, NO2, NO3, HNO2, HNO3,
                      H2SO4, HCl, Cl, Cl2, HOCl, C2H6, CH3OH, CH3CHO,
                      C3H6, CH3CN]
    tropopause-altitude: 268.75e5
    condensation-rate: {A: 1.0e-5, rhc: 0.01, rh0: 0.015}

particles:
- name: H2SO4aer
  condensation-rate: {A: 1.0e-5, rhc: 1.0, rh0: 1.05}
- name: HCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: HCCCNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: CH3CNaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H2aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C2H6aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: C4H4aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: N2Oaer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}
- name: NH3aer
  condensation-rate: {A: 1.0e-8, rhc: 1.0, rh0: 1.05}  
  
boundary-conditions:
- name: O1D
  type: short lived
- name: N2D
  type: short lived
- name: 1CH2
  type: short lived
- name: H2O
  lower-boundary: {type: mix, mix: 1e-2}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCN
  lower-boundary: {type: vdep, vdep: 7e-3}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCCCN
  lower-boundary: {type: vdep, vdep: 7e-3}
  upper-boundary: {type: veff, veff: 0.0}
- name: HNO3
  lower-boundary: {type: vdep, vdep: 2e-1}
  upper-boundary: {type: veff, veff: 0.0}
- name: O3
  lower-boundary: {type: vdep, vdep: 7e-2}
  upper-boundary: {type: veff, veff: 0.0}
- name: HNO
  lower-boundary: {type: vdep, vdep: 1}
  upper-boundary: {type: veff, veff: 0.0}
- name: NO2
  lower-boundary: {type: vdep, vdep: 3e-3}
  upper-boundary: {type: veff, veff: 0.0}
- name: "NO"
  lower-boundary: {type: vdep, vdep: 3e-4}
  upper-boundary: {type: veff, veff: 0.0}
- name: CH3
  lower-boundary: {type: vdep, vdep: 1}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2CO
  lower-boundary: {type: vdep, vdep: 2e-2}
  upper-boundary: {type: veff, veff: 0.0}
- name: HCO
  lower-boundary: {type: vdep, vdep: 1}
  upper-boundary: {type: veff, veff: 0.0}
- name: CO
  lower-boundary: {type: vdep, vdep: 1e-8}
  upper-boundary: {type: veff, veff: 0.0}
- name: H2O2
  lower-boundary: {type: vdep, vdep: 2e-1}
  upper-boundary: {type: veff, veff: 0.0}
- name: HO2
  lower-boundary: {type: vdep, vdep: 1}
  upper-boundary: {type: veff, veff: 0.0}
- name: OH
  lower-boundary: {type: vdep, vdep: 1}
  upper-boundary: {type: veff, veff: 0.0}
- name: H
  lower-boundary: {type: vdep, vdep: 1}
  upper-boundary: {type: veff, veff: 0.0}
- name: O
  lower-boundary: {type: vdep, vdep: 1}
  upper-boundary: {type: veff, veff: 0.0}



